FROM node:16.13.2-alpine3.15

WORKDIR '/app'

COPY package.json .
RUN npm install
RUN npm install -g @aws-amplify/cli

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

USER node
